### ISSUE TITLE
Build feature extraction [binning] and feature data I/O [HDF5]

### ISSUE THREAD

**Issue by hermands** [davidpng/FCS_Database#28]
Proposal is to:
* FCS subroutines
 * Add FCS_subroutines/[FCS_feature_extraction].py that bins processed data and stores in FCS attribute
 * Add FCS_subroutines/[FCS_features_to_HDF5].py that pushes feature data into HDF5 structure
* Big Matrix routines
 * Add [Process_features].py that loads/accesses HDF5 structure, reads/?loads single table in DB with meta/label/annotation data, can convert between different data formats, and ?facilitates regression/random forest/SVM
* Subcommands
  * Add subcommands/[prep_ML_analysis].py: 
   * This would query db and return file list, loop through FCS files and push data from each into FCS_subroutines/[FCS_feature_extraction].py and FCS_subroutines/[FCS_features_to_HDF5].py
   * This would also run same query on db and return a single pandas table of annotations (case-level mostly). This single table could be pushed into an analysis-specific sqlite db OR would it be straightforward to push this table into the same HDF5 file as the data (Could imagine the ability to modify this table in HDF5 without changing the feature data [to allow flexibility in annotations]??)
 * Add subcommands/[run_ML_analysis.py].py
   * This method would load in HDF5 file (features and annotations) and perform various analyses. This would likely be just a wrapper for many different methods

**Comment by davidpng** [comment]
HDF5_IO renamed to Feature_IO, new class MergedData_IO inherit similar things such as push and pull dataframes.  This now handles IO to two separate HDF5 files with different schemas and properties.
