### ISSUE TITLE
Do we want HDF5/h5py to be parrallelable?

### ISSUE THREAD

**Issue by hermands** [davidpng/FCS_Database#33]
HDF5 and h5py appear to have good support for parallelization, but require specific installation options.

I imagine this would improve FCS data processing considerably, but perhaps not worth it if we are only doing it a few times.

What about retrieving data from HDF5 object? Are we loading all into memory -- how big are we talking? Or do we want parallel access?

**Comment by davidpng** [comment]
Don't know until we try but I think that we can retrieve all extracted
features into a dense array with reasonable memory requirements.  HDF5 is
good but it is still orders of magnitude slower than RAM.
